site_name: My first git website
site_url: https://pvgenuchten.github.io/cms-training
site_description: An exersize in data training
site_author: Example Team

repo_url: https://github.com/pvgenuchten/cms-training
edit_uri: blob/master/docs

theme:
  name: material
  logo: https://lsc-hubs.org/images/logo-lsc-hubs.svg
  locale: en
  features:
    - content.action.edit

nav:
  - Home: index.md
  - About: about.md

